version: '3.8'

services:
  postgres:
    container_name: go-auth-postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
    ports:
      - ${POSTGRES_PORT_EXTERNAL}:${POSTGRES_PORT_INTERNAL}
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d:ro
      - auth-postgres:/var/lib/postgresql/data

  redis:
    container_name: go-auth-redis
    image: redis
    command: >
      --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_EXTERNAL_PORT}:${REDIS_INTERNAL_PORT}"
    volumes:
      - redis_data:/data
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - mmco-network

volumes:
  auth-postgres:
  auth-redis: